import '../models/user_model.dart';
import '../models/task_model.dart';
import '../models/bid_model.dart';
import '../models/review_model.dart';
import '../models/notification_model.dart';
import '../models/message_model.dart';

class MockDataService {
  static UserModel get currentUser => UserModel(
    id: 'user_001',
    fullName: 'Фирдавс Рахимов',
    phone: '+992 93 123 4567',
    email: 'firdavs@example.com',
    bio: 'Профессиональный сантехник с 10-летним опытом работы в Душанбе',
    role: UserRole.client,
    latitude: 38.5598,
    longitude: 68.7740,
    city: 'Душанбе',
    rating: 4.8,
    tasksCompleted: 47,
    reviewsCount: 35,
    skills: ['Сантехника', 'Ремонт', 'Установка'],
    createdAt: DateTime(2023, 3, 15),
    isVerified: true,
  );

  static List<UserModel> get workers => [
    UserModel(
      id: 'worker_001',
      fullName: 'Ахмад Каримов',
      phone: '+992 90 111 2233',
      bio: 'Устои сантехника. 15 сол таҷриба дар кори сантехникӣ.',
      role: UserRole.worker,
      latitude: 38.5650,
      longitude: 68.7800,
      city: 'Душанбе',
      rating: 4.9,
      tasksCompleted: 234,
      reviewsCount: 180,
      skills: ['Сантехника', 'Отопление', 'Канализация'],
      createdAt: DateTime(2022, 1, 10),
      isVerified: true,
    ),
    UserModel(
      id: 'worker_002',
      fullName: 'Бахром Шарипов',
      phone: '+992 91 222 3344',
      bio: 'Электромонтёр. Кори сифатнок ва боэътимод.',
      role: UserRole.worker,
      latitude: 38.5520,
      longitude: 68.7650,
      city: 'Душанбе',
      rating: 4.7,
      tasksCompleted: 156,
      reviewsCount: 120,
      skills: ['Электрика', 'Освещение', 'Проводка'],
      createdAt: DateTime(2022, 5, 20),
      isVerified: true,
    ),
    UserModel(
      id: 'worker_003',
      fullName: 'Саида Мирзоева',
      phone: '+992 92 333 4455',
      bio: 'Профессиональная уборка квартир и офисов. Быстро и чисто!',
      role: UserRole.worker,
      latitude: 38.5700,
      longitude: 68.7900,
      city: 'Душанбе',
      rating: 4.8,
      tasksCompleted: 89,
      reviewsCount: 72,
      skills: ['Уборка', 'Химчистка', 'Стирка'],
      createdAt: DateTime(2023, 2, 1),
      isVerified: true,
    ),
    UserModel(
      id: 'worker_004',
      fullName: 'Далер Назаров',
      phone: '+992 93 444 5566',
      bio: 'Мастер по ремонту бытовой техники и мебели. Гарантия на работу.',
      role: UserRole.worker,
      latitude: 38.5450,
      longitude: 68.7550,
      city: 'Душанбе',
      rating: 4.6,
      tasksCompleted: 67,
      reviewsCount: 45,
      skills: ['Ремонт техники', 'Мебель', 'Сборка'],
      createdAt: DateTime(2023, 6, 15),
      isVerified: false,
    ),
    UserModel(
      id: 'worker_005',
      fullName: 'Зарина Холова',
      phone: '+992 90 555 6677',
      bio: 'Репетитор по математике и английскому языку. Подготовка к экзаменам.',
      role: UserRole.worker,
      latitude: 38.5800,
      longitude: 68.8000,
      city: 'Душанбе',
      rating: 5.0,
      tasksCompleted: 120,
      reviewsCount: 98,
      skills: ['Математика', 'Английский', 'Подготовка к экзаменам'],
      createdAt: DateTime(2022, 9, 1),
      isVerified: true,
    ),
    UserModel(
      id: 'worker_006',
      fullName: 'Рустам Алиев',
      phone: '+992 91 666 7788',
      bio: 'Строитель. Выполню ремонт любой сложности. Опыт 12 лет.',
      role: UserRole.worker,
      latitude: 40.2850,
      longitude: 69.6300,
      city: 'Худжанд',
      rating: 4.5,
      tasksCompleted: 198,
      reviewsCount: 145,
      skills: ['Строительство', 'Штукатурка', 'Покраска'],
      createdAt: DateTime(2021, 11, 1),
      isVerified: true,
    ),
  ];

  static List<TaskModel> get tasks => [
    TaskModel(
      id: 'task_001',
      clientId: 'user_001',
      clientName: 'Фирдавс Рахимов',
      title: 'Починить кран на кухне',
      description: 'Течёт кран на кухне, нужен хороший сантехник. Кран шаровой, возможно нужна замена картриджа. Адрес: ул. Рудаки 45.',
      category: TaskCategory.plumbing,
      budget: 150,
      location: 'ул. Рудаки 45, Душанбе',
      latitude: 38.5598,
      longitude: 68.7740,
      deadline: DateTime.now().add(const Duration(days: 3)),
      status: TaskStatus.open,
      bidsCount: 3,
      createdAt: DateTime.now().subtract(const Duration(hours: 2)),
      updatedAt: DateTime.now().subtract(const Duration(hours: 2)),
    ),
    TaskModel(
      id: 'task_002',
      clientId: 'user_002',
      clientName: 'Малика Собирова',
      title: 'Установка люстры в зале',
      description: 'Нужно установить новую люстру в гостиной. Старую снять, новую повесить и подключить. Люстра уже куплена.',
      category: TaskCategory.electrical,
      budget: 200,
      location: 'мкр. Зарафшон, Душанбе',
      latitude: 38.5650,
      longitude: 68.7800,
      deadline: DateTime.now().add(const Duration(days: 2)),
      status: TaskStatus.open,
      bidsCount: 5,
      createdAt: DateTime.now().subtract(const Duration(hours: 5)),
      updatedAt: DateTime.now().subtract(const Duration(hours: 5)),
    ),
    TaskModel(
      id: 'task_003',
      clientId: 'user_003',
      clientName: 'Шахло Муродова',
      title: 'Генеральная уборка квартиры',
      description: 'Трёхкомнатная квартира, нужна генеральная уборка: мытьё окон, полов, ванной, кухни. Площадь ~85 кв.м.',
      category: TaskCategory.cleaning,
      budget: 350,
      location: 'ул. Айни 15, Душанбе',
      latitude: 38.5520,
      longitude: 68.7650,
      deadline: DateTime.now().add(const Duration(days: 1)),
      status: TaskStatus.open,
      bidsCount: 2,
      createdAt: DateTime.now().subtract(const Duration(hours: 8)),
      updatedAt: DateTime.now().subtract(const Duration(hours: 8)),
    ),
    TaskModel(
      id: 'task_004',
      clientId: 'user_004',
      clientName: 'Исмоил Саидов',
      title: 'Репетитор по математике для 9 класса',
      description: 'Ищу опытного репетитора по математике для подготовки к экзаменам. 3 раза в неделю по 1.5 часа.',
      category: TaskCategory.tutoring,
      budget: 500,
      location: 'мкр. Шохмансур, Душанбе',
      latitude: 38.5700,
      longitude: 68.7900,
      deadline: DateTime.now().add(const Duration(days: 30)),
      status: TaskStatus.inProgress,
      assignedWorkerId: 'worker_005',
      bidsCount: 4,
      createdAt: DateTime.now().subtract(const Duration(days: 3)),
      updatedAt: DateTime.now().subtract(const Duration(days: 1)),
    ),
    TaskModel(
      id: 'task_005',
      clientId: 'user_005',
      clientName: 'Навруз Ёров',
      title: 'Покраска стен в спальне',
      description: 'Спальня 16 кв.м. Нужно подготовить стены и покрасить. Краска будет предоставлена.',
      category: TaskCategory.painting,
      budget: 800,
      location: 'ул. Бохтар 92, Душанбе',
      latitude: 38.5450,
      longitude: 68.7550,
      deadline: DateTime.now().add(const Duration(days: 7)),
      status: TaskStatus.open,
      bidsCount: 6,
      createdAt: DateTime.now().subtract(const Duration(days: 1)),
      updatedAt: DateTime.now().subtract(const Duration(days: 1)),
    ),
    TaskModel(
      id: 'task_006',
      clientId: 'user_001',
      clientName: 'Фирдавс Рахимов',
      title: 'Перевезти мебель на новую квартиру',
      description: 'Нужна помощь с переездом: диван, шкаф, стиральная машина, 10 коробок. С 3 этажа на 5 этаж без лифта.',
      category: TaskCategory.moving,
      budget: 600,
      location: 'ул. Сомони 120 -> мкр. Фирдавсӣ',
      latitude: 38.5550,
      longitude: 68.7700,
      deadline: DateTime.now().add(const Duration(days: 5)),
      status: TaskStatus.open,
      bidsCount: 3,
      voiceMessageUrl: 'https://example.com/voice/task006.ogg',
      createdAt: DateTime.now().subtract(const Duration(hours: 12)),
      updatedAt: DateTime.now().subtract(const Duration(hours: 12)),
    ),
    TaskModel(
      id: 'task_007',
      clientId: 'user_006',
      clientName: 'Парвина Зоирова',
      title: 'Собрать кухонный гарнитур',
      description: 'Купили новый кухонный гарнитур. Нужен мастер для сборки и установки. 8 модулей + столешница.',
      category: TaskCategory.repair,
      budget: 1200,
      location: 'ул. Дружбы Народов 30, Душанбе',
      latitude: 38.5680,
      longitude: 68.7850,
      deadline: DateTime.now().add(const Duration(days: 4)),
      status: TaskStatus.completed,
      assignedWorkerId: 'worker_004',
      bidsCount: 7,
      createdAt: DateTime.now().subtract(const Duration(days: 10)),
      updatedAt: DateTime.now().subtract(const Duration(days: 2)),
    ),
    TaskModel(
      id: 'task_008',
      clientId: 'user_001',
      clientName: 'Фирдавс Рахимов',
      title: 'Установить кондиционер',
      description: 'Нужен монтаж сплит-системы LG 12000 BTU в спальне. Кондиционер уже куплен, нужна только установка.',
      category: TaskCategory.electrical,
      budget: 450,
      location: 'ул. Рудаки 45, Душанбе',
      latitude: 38.5598,
      longitude: 68.7740,
      deadline: DateTime.now().add(const Duration(days: 2)),
      status: TaskStatus.inProgress,
      assignedWorkerId: 'worker_002',
      bidsCount: 3,
      createdAt: DateTime.now().subtract(const Duration(days: 2)),
      updatedAt: DateTime.now().subtract(const Duration(hours: 6)),
    ),
  ];

  static List<BidModel> getBidsForTask(String taskId) {
    final allBids = <BidModel>[
      BidModel(id: 'bid_001', taskId: 'task_001', workerId: 'worker_001', workerName: 'Ахмад Каримов', workerRating: 4.9, amount: 120, message: 'Салом! Ман устои сантехника бо 15 сол таҷриба. Мушкилии шуморо зуд ислоҳ мекунам.', estimatedTime: '1-2 соат', status: BidStatus.pending, createdAt: DateTime.now().subtract(const Duration(hours: 1))),
      BidModel(id: 'bid_002', taskId: 'task_001', workerId: 'worker_004', workerName: 'Далер Назаров', workerRating: 4.6, amount: 100, message: 'Могу починить сегодня вечером. Есть все необходимые инструменты.', estimatedTime: '1 час', status: BidStatus.pending, createdAt: DateTime.now().subtract(const Duration(minutes: 30))),
      BidModel(id: 'bid_003', taskId: 'task_001', workerId: 'worker_006', workerName: 'Рустам Алиев', workerRating: 4.5, amount: 140, message: 'Готов выполнить работу качественно. Гарантия 6 месяцев.', estimatedTime: '2 часа', status: BidStatus.pending, createdAt: DateTime.now().subtract(const Duration(minutes: 15))),
      BidModel(id: 'bid_004', taskId: 'task_002', workerId: 'worker_002', workerName: 'Бахром Шарипов', workerRating: 4.7, amount: 180, message: 'Установлю люстру аккуратно. Опыт работы с электрикой 10 лет.', estimatedTime: '1.5 часа', status: BidStatus.pending, createdAt: DateTime.now().subtract(const Duration(hours: 3))),
      BidModel(id: 'bid_005', taskId: 'task_003', workerId: 'worker_003', workerName: 'Саида Мирзоева', workerRating: 4.8, amount: 300, message: 'Профессиональная уборка с моющими средствами. Работаю с помощницей.', estimatedTime: '4-5 часов', status: BidStatus.pending, createdAt: DateTime.now().subtract(const Duration(hours: 6))),
      BidModel(id: 'bid_006', taskId: 'task_005', workerId: 'worker_006', workerName: 'Рустам Алиев', workerRating: 4.5, amount: 700, message: 'Опыт покраски 8 лет. Подготовка стен включена в цену.', estimatedTime: '2 дня', status: BidStatus.pending, createdAt: DateTime.now().subtract(const Duration(hours: 20))),
      BidModel(id: 'bid_007', taskId: 'task_008', workerId: 'worker_002', workerName: 'Бахром Шарипов', workerRating: 4.7, amount: 400, message: 'Установлю кондиционер профессионально. Гарантия 1 год.', estimatedTime: '3 часа', status: BidStatus.accepted, createdAt: DateTime.now().subtract(const Duration(days: 2))),
      // Bids from current user (user_001) as master on other users' tasks
      BidModel(id: 'bid_u01', taskId: 'task_002', workerId: 'user_001', workerName: 'Фирдавс Рахимов', workerRating: 4.8, amount: 150, message: 'Установлю люстру быстро и качественно. Имею все инструменты.', estimatedTime: '1 час', status: BidStatus.pending, createdAt: DateTime.now().subtract(const Duration(hours: 2))),
      BidModel(id: 'bid_u02', taskId: 'task_003', workerId: 'user_001', workerName: 'Фирдавс Рахимов', workerRating: 4.8, amount: 280, message: 'Профессиональная генеральная уборка. Все средства свои.', estimatedTime: '3-4 часа', status: BidStatus.accepted, createdAt: DateTime.now().subtract(const Duration(days: 1))),
      BidModel(id: 'bid_u03', taskId: 'task_004', workerId: 'user_001', workerName: 'Фирдавс Рахимов', workerRating: 4.8, amount: 500, message: 'Ремонт мебели — мой профиль. Сделаю аккуратно и по сроку.', estimatedTime: '1 день', status: BidStatus.pending, createdAt: DateTime.now().subtract(const Duration(hours: 5))),
      BidModel(id: 'bid_u04', taskId: 'task_005', workerId: 'user_001', workerName: 'Фирдавс Рахимов', workerRating: 4.8, amount: 650, message: 'Покраска стен — опыт 5 лет. Качественная работа с гарантией.', estimatedTime: '2 дня', status: BidStatus.rejected, createdAt: DateTime.now().subtract(const Duration(days: 3))),
      BidModel(id: 'bid_u05', taskId: 'task_007', workerId: 'user_001', workerName: 'Фирдавс Рахимов', workerRating: 4.8, amount: 350, message: 'Соберу мебель аккуратно по инструкции. Быстро и качественно.', estimatedTime: '2 часа', status: BidStatus.accepted, createdAt: DateTime.now().subtract(const Duration(days: 5))),
    ];
    return allBids.where((b) => b.taskId == taskId).toList();
  }

  static List<ReviewModel> getReviewsForUser(String userId) {
    return [
      ReviewModel(id: 'rev_001', taskId: 'task_007', reviewerId: 'user_006', reviewerName: 'Парвина Зоирова', targetUserId: userId, rating: 5.0, comment: 'Отличный мастер! Собрал кухню быстро и качественно. Рекомендую!', createdAt: DateTime.now().subtract(const Duration(days: 2))),
      ReviewModel(id: 'rev_002', taskId: 'task_004', reviewerId: 'user_004', reviewerName: 'Исмоил Саидов', targetUserId: userId, rating: 4.5, comment: 'Хороший репетитор, ребёнок доволен. Терпеливая и объясняет понятно.', createdAt: DateTime.now().subtract(const Duration(days: 5))),
      ReviewModel(id: 'rev_003', taskId: 'task_001', reviewerId: 'user_001', reviewerName: 'Фирдавс Рахимов', targetUserId: userId, rating: 4.8, comment: 'Усто зуд омад ва кори сифатнок кард. Ташаккур!', createdAt: DateTime.now().subtract(const Duration(days: 8))),
    ];
  }

  static List<NotificationModel> getNotifications() {
    return [
      NotificationModel(id: 'notif_001', title: 'Новый отклик', message: 'Ахмад Каримов откликнулся на «Починить кран на кухне»', type: NotificationType.newBid, relatedTaskId: 'task_001', createdAt: DateTime.now().subtract(const Duration(hours: 1))),
      NotificationModel(id: 'notif_002', title: 'Новый отклик', message: 'Далер Назаров предложил 100 TJS за починку крана', type: NotificationType.newBid, relatedTaskId: 'task_001', createdAt: DateTime.now().subtract(const Duration(minutes: 30))),
      NotificationModel(id: 'notif_003', title: 'Задача завершена', message: '«Собрать кухонный гарнитур» — работа выполнена!', type: NotificationType.taskCompleted, relatedTaskId: 'task_007', isRead: true, createdAt: DateTime.now().subtract(const Duration(days: 2))),
      NotificationModel(id: 'notif_004', title: 'Новый отзыв', message: 'Парвина Зоирова оставила отзыв: 5.0★', type: NotificationType.newReview, createdAt: DateTime.now().subtract(const Duration(days: 2))),
      NotificationModel(id: 'notif_005', title: 'Отклик принят!', message: 'Бахром Шарипов начинает работу по установке кондиционера', type: NotificationType.bidAccepted, relatedTaskId: 'task_008', isRead: true, createdAt: DateTime.now().subtract(const Duration(days: 2))),
      NotificationModel(id: 'notif_006', title: 'Добро пожаловать!', message: 'Добро пожаловать в Hunar — маркетплейс услуг Таджикистана!', type: NotificationType.system, isRead: true, createdAt: DateTime.now().subtract(const Duration(days: 30))),
    ];
  }

  static List<ChatThread> getChatThreads() {
    return [
      ChatThread(
        id: 'thread_001',
        participantId: 'worker_001',
        participantName: 'Ахмад Каримов',
        taskId: 'task_001',
        taskTitle: 'Починить кран на кухне',
        messages: [
          ChatMessage(id: 'msg_001', senderId: 'worker_001', senderName: 'Ахмад Каримов', content: 'Салом! Ман метавонам имрӯз баъди соати 3 биёям. Картридж барои крани шумо дорам.', sentAt: DateTime.now().subtract(const Duration(hours: 1)), isRead: true),
          ChatMessage(id: 'msg_002', senderId: 'user_001', senderName: 'Фирдавс Рахимов', content: 'Хуб, интизори шумо мешавам! Адрес: Рудаки 45, хонаи 12.', sentAt: DateTime.now().subtract(const Duration(minutes: 50)), isRead: true),
          ChatMessage(id: 'msg_003', senderId: 'worker_001', senderName: 'Ахмад Каримов', content: 'Фаҳмидам, ташаккур! Ман дар роҳ мебошам.', sentAt: DateTime.now().subtract(const Duration(minutes: 30))),
        ],
        lastActivity: DateTime.now().subtract(const Duration(minutes: 30)),
      ),
      ChatThread(
        id: 'thread_002',
        participantId: 'worker_002',
        participantName: 'Бахром Шарипов',
        taskId: 'task_008',
        taskTitle: 'Установить кондиционер',
        messages: [
          ChatMessage(id: 'msg_004', senderId: 'worker_002', senderName: 'Бахром Шарипов', content: 'Здравствуйте! Модель кондиционера LG 12000 BTU, верно? Нужен ли дополнительный кабель?', sentAt: DateTime.now().subtract(const Duration(hours: 6)), isRead: true),
          ChatMessage(id: 'msg_005', senderId: 'user_001', senderName: 'Фирдавс Рахимов', content: 'Да, всё верно. Кабель тоже есть. Когда сможете приехать?', sentAt: DateTime.now().subtract(const Duration(hours: 5)), isRead: true),
        ],
        lastActivity: DateTime.now().subtract(const Duration(hours: 5)),
      ),
    ];
  }
}
